#!/bin/sh

DOTFILES_SRC=git@github.com:lihop/dotfiles.git
DOTFILES_DIR=$HOME/.dotfiles

download() {
    git clone $DOTFILES_SRC $DOTFILES_DIR  
}

update() {
    if [ ! -d $DOTFILES_DIR ]; then
        download
        cd $DOTFILES_DIR
    else
        cd $DOTFILES_DIR
        git pull
    fi
    rm ~/.Xresources # Remove to avoid conflicts
    for dir in */; do
        stow $dir
    done
}

update
